import React from 'react';

const GeneralSettings = () => {
    return (<></>)
};

export default GeneralSettings;

export type GeneralSettingsType = {
    noGoogleStun: boolean,
    noVideoDevice: boolean,
    noAudioDevice: boolean,
    forceI420: boolean,
    hwMjpegDecoder: boolean,
    videoDevice: string,
    resolution: string,
    framerate: number,
    fixedResolution: boolean,
    priority: 'BALANCE' | 'FRAMERATE' | 'RESOLUTION',
    useSdl: boolean,
    showMe: boolean,
    windowWidth: number,
    windowHeight: number,
    fullscreen: boolean,
    insecure: boolean,
    logLevel: 'verbose' | 'info' | 'warning' | 'error' | 'none',
    screenCapture: boolean,
    metricsPort: number,
    metricsAllowExternalIp: boolean,
    disableEchoCancellation: boolean,
    disableAutoGainControl: boolean,
    disableNoiseSuppression: boolean,
    disableHighpassFilter: boolean,
    disableTypingDetection: boolean,
    disableResidualEchoDet: boolean,
    vp8Encoder: 'default' | 'software',
    vp8Decoder: 'default' | 'software',
    vp9Encoder: 'default' | 'software',
    vp9Decoder: 'default' | 'software',
    av1Encoder: 'default' | 'software',
    av1Decoder: 'default' | 'software',
    h264Encoder: 'default' | 'videotoolbox',
    h264Decoder: 'default' | 'videotoolbox',
    serial: string
};

export const defaultGeneralSettings: GeneralSettingsType = {
    noGoogleStun: false,
    noVideoDevice: false,
    noAudioDevice: false,
    forceI420: false,
    hwMjpegDecoder: false,
    videoDevice: '',
    resolution: 'VGA',
    framerate: 30,
    fixedResolution: false,
    priority: 'BALANCE',
    useSdl: false,
    showMe: false,
    windowWidth: 640,
    windowHeight: 480,
    fullscreen: false,
    insecure: false,
    logLevel: 'none',
    screenCapture: false,
    metricsPort: -1,
    metricsAllowExternalIp: false,
    disableEchoCancellation: false,
    disableAutoGainControl: false,
    disableNoiseSuppression: false,
    disableHighpassFilter: false,
    disableTypingDetection: false,
    disableResidualEchoDet: false,
    vp8Encoder: 'default',
    vp8Decoder: 'default',
    vp9Encoder: 'default',
    vp9Decoder: 'default',
    av1Encoder: 'default',
    av1Decoder: 'default',
    h264Encoder: 'default',
    h264Decoder: 'default',
    serial: ''
}