export type GeneralSettings = {
    noGoogleStun: boolean,
    noVideoDevice: boolean,
    noAudioDevice: boolean,
    forceI420: boolean,
    hwMjpegDecoder: boolean,
    videoDevice: string,
    resolution: string,
    framerate: number,
    fixedResolution: boolean,
    priority: 'BALANCE' | 'FRAMERATE' | 'RESOLUTION',
    useSdl: boolean,
    showMe: boolean,
    windowWidth: number,
    windowHeight: number,
    fullscreen: boolean,
    insecure: boolean,
    logLevel: 'verbose' | 'info' | 'warning' | 'error' | 'none',
    screenCapture: boolean,
    disableEchoCancellation: boolean,
    disableAutoGainControl: boolean,
    disableNoiseSuppression: boolean,
    disableHighpassFilter: boolean,
    disableTypingDetection: boolean,
    disableResidualEchoDet: boolean,
    videoCodecEngines: boolean,
    vp8Encoder: 'default' | 'software',
    vp8Decoder: 'default' | 'software',
    vp9Encoder: 'default' | 'software',
    vp9Decoder: 'default' | 'software',
    av1Encoder: 'default' | 'software',
    av1Decoder: 'default' | 'software',
    h264Encoder: 'default' | 'videotoolbox',
    h264Decoder: 'default' | 'videotoolbox',
    serial: string
};